---
title: "Visão dos votos"
author: "Nazareno Andrade e João Arthur B. Monteiro"
date: "30 de maio de 2015"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
require(cluster)
require(ade4)
require(scales)

source("R/camara-lib.R")

# para instalar o rCharts:
# require(devtools)
# install_github('rCharts', 'ramnathv')
require("rCharts")
```

```{r}
votos <- ler_votos_de_ativos("votacoes.csv")
# distinguir diferentes votações de uma mesma proposição
votos$num_pro <- paste0(votos$num_pro, "-", votos$id_votacao)
```


```{r}
votacao <- votos %>% 
  select(nome, partido, uf, num_pro, voto)
# versão do dataframe com recomendações do PMDB sendo a
# votação de Eduardo Cunha:
ec.v <- votos %>% 
  select(num_pro, cunha) %>% 
  filter(cunha %in% c("sim", "não")) %>% 
  unique()

ec <- cbind(data.frame(nome = "Eduardo Cunha", 
                       partido = "pmdb", 
                       uf = "rj"), 
            ec.v)
names(ec) <- names(votacao)
# esse é o df com cunha:
votacao.cc <- rbind(votacao, ec)
```

```{r}
# TODO para agrupar:
# dispensar a coluna de nome 
#rownames(votacao.cast) <- votacao.cast$nome
#votacao.cast <- select(votacao.cast, -1)
#diss <- daisy(votacao.cast[,2:ncol(votacao.cast)], metric = "gower") # stand = FALSE?
```

```{r}
require(FactoMineR)

votacao.cast <- dcast(votacao.cc, 
                      nome + partido + uf ~ num_pro, 
                      value.var = "voto")
votacao.cast <- as.data.frame(apply(votacao.cast, 2, as.factor))

# TODO DEIXAR "Average"?
mca1 = MCA(votacao.cast, 
           ncp = 2,
           graph = FALSE,
           quali.sup = c(1:3),
           na.method = "Average")

# data frame with observation coordinates
mca1_obs_df = data.frame(mca1$ind$coord, 
                         nome = votacao.cast$nome,
                         partido = votacao.cast$partido, 
                         uf = votacao.cast$uf)

# Alguns notáveis: 
# "Tiririca", "Luiz Couto", "Jandira Fegalli", "Marco Feliciano", "Romário", "Celso Russomano", "Lindemberg Farias", "Manoela D'Ávila", "Chico Alencar"
mca1_obs_df$destaque <- mca1_obs_df$nome %in% c("Tiririca", 
                                                "Pr. Marco Feliciano", 
                                                "Jair Bolsonaro", 
                                                "Luiz Couto", 
                                                "Jandira Feghali",
                                                "Jean Wyllys", 
                                                "Veneziano Vital do Rêgo")

# Os da PB
mca1_obs_df$destaque_pb <- ifelse(mca1_obs_df$uf == "PB", "PB", "Demais estados")

# Partidos icônicos
mca1_obs_df$destaque_partido = factor(ifelse(mca1_obs_df$partido %in% 
                                               c("pmdb", "psdb", "pt", "psol"), 
                                             as.character(mca1_obs_df$partido), 
                                             "outros"))

# E E. Cunha
mca1_obs_df$destaque_cunha <- ifelse(mca1_obs_df$nome == "Eduardo Cunha", TRUE, FALSE)


```

Visão geral

```{r}
plotMCA <- function(dados){
  ggplot(data = semcunha, aes(x = Dim.1, y = Dim.2, label = nome)) +
    geom_hline(yintercept = 0, colour = "gray70") +
    geom_vline(xintercept = 0, colour = "gray70") +
    #geom_point(colour = "gray50", alpha = 0.7) +
    geom_text(colour = "gray50", alpha = 0.7, size =3) +
    #geom_density2d(colour = "gray75") +
    ylab("") + xlab("")+ 
    theme_classic() + 
    theme(axis.ticks = element_blank(), 
          axis.text = element_blank(), 
          axis.line = element_blank())
}

# plot of variable categories
semcunha <- filter(mca1_obs_df, nome != "Eduardo Cunha")
p <- plotMCA(semcunha)
p

png("visao-geral.png", width = 800, height = 600)
p
dev.off()

png("visao-geral-gg.png", width = 1500, height = 1200)
p
dev.off()

p <- p + geom_point(data = filter(mca1_obs_df, nome == "Eduardo Cunha"), 
                    colour = "darkred", 
                    size = 15, 
                    alpha = 0.7)

png("visao-geral-cc.png", width = 800, height = 600)
p
dev.off()

```

Alguns ilustres

```{r}
p <- ggplot(data = semcunha, 
            aes(x = Dim.1, y = Dim.2, label = nome, colour = destaque, size = destaque)) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_text() +
  scale_size_manual(values = c(3.2, 4)) + 
  scale_colour_manual(values = c(alpha("grey70", .6), 
                                 alpha("black", 1))) + 
  ylab("") + xlab("")+ 
  theme_classic() + 
  theme(legend.position = "none", 
        axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        axis.line = element_blank())

p
png("icones.png", 
    width = 800, height = 600)
p
dev.off()

```

Partidos

```{r}
p <- ggplot(data = semcunha, 
       aes(x = Dim.1, y = Dim.2, label = nome, 
           colour = destaque_partido)) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_text(size = 3.) +
  scale_colour_manual(values = c(alpha("grey70", .6), 
                                 alpha("darkred", 1), 
                                 alpha("#0066CC", 1),
                                 alpha("#E69F00", 1),
                                 alpha("#FF3300", 1)
                                 ), 
                      guide = guide_legend(title = "partido", 
                                           override.aes = list(alpha = 1, size = 4))) + 
  ylab("") + xlab("")+ 
  theme_classic() + 
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        axis.line = element_blank())
p
png("partidos.png", 
    width = 800, height = 600)
p
dev.off()

png("partidos-gg.png", width = 1500, height = 1200)
p
dev.off()
```

O pessoal da PB 

```{r}
p <- ggplot(data = semcunha, 
            aes(x = Dim.1, 
                y = Dim.2, 
                label = nome, 
                colour = destaque_pb, 
                size = destaque_pb == "PB")) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_text() +
  scale_colour_manual(values = c(alpha("grey70", .5), 
                                 alpha("black", 1))) + 
  scale_size_manual(values = c(3.2, 4)) + 
  ylab("") + xlab("")+ 
  theme_classic() + 
  theme(legend.position = "none", 
        axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        axis.line = element_blank())
p
png("deputados-da-pb.png", 
    width = 800, height = 600)
p
dev.off()

```

# Interativo

```{r}
options(RCHART_WIDTH = 800, RCHART_HEIGHT = 500)
n1 <- nPlot(Dim.2 ~ Dim.1, 
            group = 'destaque_partido', 
            data = semcunha, 
            type = "scatterChart")
n1$chart(color = c("#BDBDBD", "#FF3300", "darkred", "#0066CC", "#E69F00"))
n1$chart(tooltipContent = "#! function(key, x, y, e){ 
  return e.point.nome + ', ' + (e.point.partido.toUpperCase()) + '(' + (e.point.uf) + ')';
} !#")
n1$chart(tooltipXContent = NA, tooltipYContent = NA)
n1$chart(sizeRange = c(50,50))
n1$chart(showXAxis = FALSE, showYAxis = FALSE)
n1

n1$save("partidosdestaque.html", cdn=TRUE)
#n1$publish('House of Cunha - alguns partidos', host = 'gist')
sink("viz-inline.html")
cat(n1$show('inline', include_assets = TRUE, cdn = TRUE))
sink()
n1
```



