---
title: "afinidade"
output: html_document
---

Monta um ranking com os deputados mais próximos para cada deputado

```{r}
library(e1071)
library(tidyr)

source("R/camara-lib.R")
```

Carrega os dados

```{r}
votos_por_deputado1 <- recuperar_votos_por_deputado(arquivo.votos = "dados/votacoes.csv", corrigir.migracoes = TRUE)


votos_por_deputado <- head(votos_por_deputado1)


rownames(votos_por_deputado) <- votos_por_deputado$id_dep

votos_por_deputado <- votos_por_deputado[,5:ncol(votos_por_deputado)]

votos_por_deputado[] <- lapply(votos_por_deputado, as.character)
votos_por_deputado[is.na(votos_por_deputado)] <- 0
votos_por_deputado <- as.matrix(votos_por_deputado)

votos_por_deputado <- as.data.frame(hamming.distance(votos_por_deputado))

top_afinidade <- as.data.frame(cbind(row.names(votos_por_deputado), apply(votos_por_deputado, 1, function(x) names(votos_por_deputado)[which(x == min(x))])))



n <- length(votos_por_deputado)

top_not_afinidade <- as.data.frame(cbind(row.names(votos_por_deputado), apply(votos_por_deputado, 1, function(x) names(votos_por_deputado)[which(x == max(x))])))

top_not_afinidade_2 <- as.data.frame(cbind(row.names(votos_por_deputado), apply(votos_por_deputado, 1, function(x) names(votos_por_deputado)[which(x == max(sort(x,partial=n-1)[n-1]))])))

top_not_afinidade_3 <- as.data.frame(cbind(row.names(votos_por_deputado), apply(votos_por_deputado, 1, function(x) names(votos_por_deputado)[which(x == max(sort(x,partial=n-2)[n-2]))])))

top_not_afinidade_4 <- as.data.frame(cbind(row.names(votos_por_deputado), apply(votos_por_deputado, 1, function(x) names(votos_por_deputado)[which(x == max(sort(x,partial=n-3)[n-3]))])))

top_not_afinidade_5 <- as.data.frame(cbind(row.names(votos_por_deputado), apply(votos_por_deputado, 1, function(x) names(votos_por_deputado)[which(x == max(sort(x,partial = n-4)[n-4]))])))


col_list_to_number <- function(data_frame){
  top_not_afinidade <- as.data.frame(cbind(row.names(votos_por_deputado), apply(votos_por_deputado, 1, function(x) names(votos_por_deputado)[which(x == max(x))])))

  l1 <- sapply(data_frame$V2, length)
  unlist.col1 <- rep(data_frame$V1, l1)
  id_dep <- unlist(unlist.col1)
  
  not_afinidade <- unnest(data_frame, V2)
  
  df <- cbind(id_dep, not_afinidade)
  df$id_dep <- as.integer(as.character(df$id_dep))
  
  df$V1 <- NULL
  
  df
}

df_3 <- col_list_to_number(top_not_afinidade_3)
df_2 <- col_list_to_number(top_not_afinidade_2)
df_4 <- col_list_to_number(top_not_afinidade_4)


a <- as.data.frame(unique(df_2$id_dep))
colnames(a) <- c("id_dep")


aa <- c("a", "b", "c", "b")
bb <- c("a", "b", "c", "b")

cc <- rbind(aa, bb)

aa[!duplicated(cc)]

join <- left_join(a, df_3, by = "id_dep")

join <- left_join(df_2, df_3, by = "id_dep")

join1 <- left_join(join, df_4, by = "id_dep")

join1[n_distinct(join1[1,])]



join1 <- left_join(join, df_4, by = "id_dep")

library(tidyr)

a <- spread(df_3, V2, teste)

DF[!duplicated(DF$ID), ]

c <- apply(join1, 1, duplicated) %>% apply(2, sum)

join1$del <- c

join1 <- filter(join1, del < 1)

a <- apply(join1, 2, duplicated) 
a[,1]

join1$del <- a[,1]

join1 <- filter(join1, del == 0)






MCA_new <- read.csv("~/Projetos/houseofcunha-interface/graficos/MCA_new.csv")

toPlot <- left_join(MCA_new, df_not_afinidade, by = "id_dep")

toPlot$not_afinidade <- toPlot$V2
toPlot$V2 <- NULL

write.csv2(toPlot, file = "~/Projetos/houseofcunha-interface/graficos/MCA_new.csv", row.names = FALSE)

# TO DO ARRUMAR O CÓDIGO E MELHORAR A FUNÇÃO

```
