---
title: "bancadas-camara"
author: "Rodolfo Viana"
date: "09-12-2015"
output: html_document
---

Comparação das composições das bancadas na câmara

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
library(ggplot2)
library(reshape2)
require(cluster)
require(ade4)
require(scales)
require(FactoMineR)
library(ggthemes)
library(dplyr)

source("R/camara-lib.R")
```

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
votos_por_deputado <- recuperar_votos_por_deputado(arquivo.votos = "dados/votacoes.csv", corrigir.migracoes = TRUE)

# Bancadas 
bancada.bala <- read.table("dados/bancada-bala.csv", header=TRUE, quote="\"")
bancada.direitos.humanos <- read.table("dados/bancada-direitos-humanos.csv", header=TRUE, quote="\"")
bancada.sindical <- read.table("dados/bancada-sindical.csv", header=TRUE, quote="\"")
bancada.evangelica <- read.table("dados/bancada-evangelica.csv", header=TRUE, quote="\"")
bancada.ruralista <- read.table("dados/bancada-ruralista.csv", header=TRUE, quote="\"")
```

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
mca <- MCA(votos_por_deputado, 
           ncp = 6, # Default is 5 
           graph = FALSE,
           quali.sup = c(1:4),
           na.method = "Average") # NA or Average

mca_obs_df <-  data.frame(mca$ind$coord, 
                           nome = votos_por_deputado$nome,
                           partido = votos_por_deputado$partido, 
                           uf = votos_por_deputado$uf,
                           id_dep = votos_por_deputado$id_dep)

mca_obs_df$id_dep <- as.integer(as.character(mca_obs_df$id_dep))

#Criação do clust
hcpc <- clusterizar(mca,4)
clusters <- obter_clusters(hcpc)

mca_obs_df <- cbind(mca_obs_df, select(clusters,clust))
mca_obs_df$clust <- as.factor(mca_obs_df$clust)

# Destaque dos deputados que participam da bancada bala
mca_obs_df$destaque_bancada_bala <-  mca_obs_df$nome %in% bancada.bala$Bala

# Destaque dos deputados que participam da bancada dos direitos humanos
mca_obs_df$destaque_bancada_direitos_humanos <-  mca_obs_df$nome %in% bancada.direitos.humanos$Humanista

# Bancada Evangelica 
mca_obs_df$destaque_bancada_evangelica <- mca_obs_df$nome %in% bancada.evangelica$Evangelica

# Bancada Ruralista
mca_obs_df$destaque_bancada_ruralista <- mca_obs_df$nome %in% bancada.ruralista$Ruralista

# Bancada Sindical
mca_obs_df$destaque_bancada_sindical <- mca_obs_df$nome %in% bancada.sindical$Sindical

levels(mca_obs_df$clust) <- c("Governo", "Alinhados com PMDB", "Oposição de esquerda", "Oposição")
```

Bancada Bala 

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
# Destaque dos deputados que fazem parte da bancada da bala 
p <- plotCluster(mca_obs_df) + 
  geom_point(data = filter(mca_obs_df, destaque_bancada_bala == TRUE), 
             size = 9, alpha = 0.3, colour = "Black")  +
  coord_equal() 

png("plot/bancadas/bancada_bala_clust.png", width = 800, height = 600)
p 
dev.off()

# Nome dos deputados que fazem parte da bancada da bala 
png("plot/bancadas/bancada_bala_nomes.png", width = 800, height = 600)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_bala == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 3, hjust = -.15)
dev.off()

x<-filter(mca_obs_df, destaque_bancada_bala == TRUE)

png("plot/bancadas/bancada_bala_nomes_gg.png", width = 4000, height = 3000)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_bala == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 9, hjust = -.15) 
dev.off()  

# Número de deputados da bancada por clust
n_dep <- mca_obs_df %>% 
  filter(destaque_bancada_bala == TRUE) %>% 
  select(clust) %>% 
  table()

p <- ggplot(data = filter(mca_obs_df, destaque_bancada_bala), 
            aes(x = reorder(clust, n_dep[clust]), fill = clust)) + 
  geom_bar(width = .5) + 
  theme_pander() + 
  scale_fill_manual(values = c("#fdcdac", "#f4cae4", "#b3e2cd", "#cbd5e8")) +
  labs(y='Nº de Deputados', x='') +
  theme(axis.ticks = element_blank(), 
        axis.text = element_text(size = rel(1.5)), 
        legend.position="none") + 
  coord_flip()

png("plot/bancadas/bancada_bala_n_clust.png", width = 850, height = 500)
p 
dev.off()

# Proporção dos deputados que fazem parte da bancada da bala 
toPlot <- mca_obs_df %>% 
  group_by(clust, destaque_bancada_bala) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>% 
  ungroup() %>% 
  arrange(clust, -destaque_bancada_bala, perc)

p <- ggplot(toPlot, aes(x = clust, y = perc, fill = destaque_bancada_bala)) +  
  geom_bar(stat = "identity", width = .4) + 
  theme_pander() + 
  scale_y_continuous(labels=percent) + 
  labs(x = "", y = "% dos deputados que são da bancada da bala") + 
  theme(legend.position="none", 
        axis.text = element_text(size = rel(1.5))) + 
  scale_fill_brewer(palette = "OrRd") + 
  coord_flip()

png("plot/bancadas/bancada_bala_proporcao_clust.png", width = 850, height = 500)
p
dev.off()
```

Bancada evangelica

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
# Destaque dos deputados que fazem parte da bancada evangelica 
p <- plotCluster(mca_obs_df) + 
  geom_point(data = filter(mca_obs_df, destaque_bancada_evangelica == TRUE), 
             size = 9, alpha = 0.3, colour = "Black")  +
  coord_equal() 

png("plot/bancadas/bancada_evangelica_clust.png", width = 800, height = 600)
p 
dev.off()

# Nome dos deputados que fazem parte da bancada evangelica 
png("plot/bancadas/bancada_evangelica_nomes.png", width = 800, height = 600)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_evangelica == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 3, hjust = -.15)
dev.off()

png("plot/bancadas/bancada_evangelica_gg.png", width = 4000, height = 3000)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_evangelica == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 9, hjust = -.15) 
dev.off()  

# Número de deputados da bancada por clust
n_dep <- mca_obs_df %>% 
  filter(destaque_bancada_evangelica == TRUE) %>% 
  select(clust) %>% 
  table()

p <- ggplot(data = filter(mca_obs_df, destaque_bancada_evangelica), 
            aes(x = reorder(clust, n_dep[clust]), fill = clust)) + 
  geom_bar(width = .5) + 
  theme_pander() + 
  scale_fill_manual(values = c("#fdcdac", "#f4cae4", "#b3e2cd", "#cbd5e8")) +
  labs(y='Nº de Deputados', x='') +
  theme(axis.ticks = element_blank(), 
        axis.text = element_text(size = rel(1.5)), 
        legend.position="none") + 
  coord_flip()

png("plot/bancadas/bancada_evangelica_n_clust.png", width = 850, height = 500)
p 
dev.off()

# Proporção dos deputados que fazem parte da bancada evangelica
toPlot <- mca_obs_df %>% 
  group_by(clust, destaque_bancada_evangelica) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>% 
  ungroup() %>% 
  arrange(clust, -destaque_bancada_evangelica, perc)

p <- ggplot(toPlot, aes(x = clust, y = perc, fill = destaque_bancada_evangelica)) +  
  geom_bar(stat = "identity", width = .4) + 
  theme_pander() + 
  scale_y_continuous(labels=percent) + 
  labs(x = "", y = "% dos deputados que são da bancada evangelica") + 
  theme(legend.position="none", 
        axis.text = element_text(size = rel(1.5))) + 
  scale_fill_brewer(palette = "OrRd") + 
  coord_flip()

png("plot/bancadas/bancada_evangelica_proporcao_clust.png", width = 850, height = 500)
p
dev.off()
```

Bancada ruralista

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
# Destaque dos deputados que fazem parte da bancada ruralista 
p <- plotCluster(mca_obs_df) + 
  geom_point(data = filter(mca_obs_df, destaque_bancada_ruralista == TRUE), 
             size = 9, alpha = 0.3, colour = "Black")  +
  coord_equal() 

png("plot/bancadas/bancada_ruralista_clust.png", width = 800, height = 600)
p 
dev.off()

# Nome dos deputados que fazem parte da bancada ruralista 
png("plot/bancadas/bancada_ruralista_nomes.png", width = 800, height = 600)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_ruralista == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 3, hjust = -.15)
dev.off()

png("plot/bancadas/bancada_ruralista_gg.png", width = 4000, height = 3000)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_ruralista == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 9, hjust = -.15) 
dev.off()  

# Número de deputados da bancada por clust
n_dep <- mca_obs_df %>% 
  filter(destaque_bancada_ruralista == TRUE) %>% 
  select(clust) %>% 
  table()

p <- ggplot(data = filter(mca_obs_df, destaque_bancada_ruralista), 
            aes(x = reorder(clust, n_dep[clust]), fill = clust)) + 
  geom_bar(width = .5) + 
  theme_pander() + 
  scale_y_continuous(limits = c(0, max(n_dep)+5)) +  
  scale_fill_manual(values = c("#fdcdac", "#f4cae4", "#b3e2cd", "#cbd5e8")) +
  labs(y='Nº de Deputados', x='') +
  theme(axis.ticks = element_blank(), 
        axis.text = element_text(size = rel(1.5)), 
        legend.position="none") + 
  coord_flip()

png("plot/bancadas/bancada_ruralista_n_clust.png", width = 850, height = 500)
p 
dev.off()

# Proporção dos deputados que fazem parte da bancada ruralista
toPlot <- mca_obs_df %>% 
  group_by(clust, destaque_bancada_ruralista) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>% 
  ungroup() %>% 
  arrange(clust, -destaque_bancada_ruralista, perc)

p <- ggplot(toPlot, aes(x = clust, y = perc, fill = destaque_bancada_ruralista)) +  
  geom_bar(stat = "identity", width = .4) + 
  theme_pander() + 
  scale_y_continuous(labels=percent) + 
  labs(x = "", y = "% dos deputados que são da bancada ruralista") + 
  theme(legend.position="none", 
        axis.text = element_text(size = rel(1.5))) + 
  scale_fill_brewer(palette = "OrRd") + 
  coord_flip()

png("plot/bancadas/bancada_ruralista_proporcao_clust.png", width = 850, height = 500)
p
dev.off()
```

Bancada sindical

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
# Destaque dos deputados que fazem parte da bancada sindical 
p <- plotCluster(mca_obs_df) + 
  geom_point(data = filter(mca_obs_df, destaque_bancada_sindical == TRUE), 
             size = 9, alpha = 0.3, colour = "Black")  +
  coord_equal() 

png("plot/bancadas/bancada_sindical_clust.png", width = 800, height = 600)
p 
dev.off()

# Nome dos deputados que fazem parte da bancada sindical 
png("plot/bancadas/bancada_sindical_nomes.png", width = 800, height = 600)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_sindical == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 3, hjust = -.15)
dev.off()

png("plot/bancadas/bancada_sindical_gg.png", width = 4000, height = 3000)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_sindical == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 9, hjust = -.15) 
dev.off()  

# Número de deputados da bancada por clust
n_dep <- mca_obs_df %>% 
  filter(destaque_bancada_sindical == TRUE) %>% 
  select(clust) %>% 
  table()

p <- ggplot(data = filter(mca_obs_df, destaque_bancada_sindical), 
            aes(x = reorder(clust, n_dep[clust]), fill = clust)) + 
  geom_bar(width = .5) + 
  theme_pander() + 
  scale_fill_manual(values = c("#fdcdac", "#f4cae4", "#b3e2cd", "#cbd5e8")) +
  labs(y='Nº de Deputados', x='') +
  theme(axis.ticks = element_blank(), 
        axis.text = element_text(size = rel(1.5)), 
        legend.position="none") + 
  coord_flip()

png("plot/bancadas/bancada_sindical_n_clust.png", width = 850, height = 500)
p 
dev.off()

# Proporção dos deputados que fazem parte da bancada sindical
toPlot <- mca_obs_df %>% 
  group_by(clust, destaque_bancada_sindical) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>% 
  ungroup() %>% 
  arrange(clust, -destaque_bancada_sindical, perc)

p <- ggplot(toPlot, aes(x = clust, y = perc, fill = destaque_bancada_sindical)) +  
  geom_bar(stat = "identity", width = .4) + 
  theme_pander() + 
  scale_y_continuous(labels=percent) + 
  labs(x = "", y = "% dos deputados que são da bancada sindical") + 
  theme(legend.position="none", 
        axis.text = element_text(size = rel(1.5))) + 
  scale_fill_brewer(palette = "OrRd") + 
  coord_flip()

png("plot/bancadas/bancada_sindical_proporcao_clust.png", width = 850, height = 500)
p
dev.off()
```

Bancada dos direitos humanos

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
# Destaque dos deputados que fazem parte da bancada dos direitos humanos 
p <- plotCluster(mca_obs_df) + 
  geom_point(data = filter(mca_obs_df, destaque_bancada_direitos_humanos == TRUE), 
             size = 9, alpha = 0.3, colour = "Black")  +
  coord_equal() 

png("plot/bancadas/bancada_direitos_humanos_clust.png", width = 800, height = 600)
p 
dev.off()

# Nome dos deputados que fazem parte da bancada dos direitos humanos 
png("plot/bancadas/bancada_direitos_humanos_nomes.png", width = 800, height = 600)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_direitos_humanos == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 3, hjust = -.15)
dev.off()

png("plot/bancadas/bancada_direitos_humanos_nomes_gg.png", width = 4000, height = 3000)

p + geom_text(data = filter(mca_obs_df, destaque_bancada_direitos_humanos == TRUE), 
                   aes(x = Dim.1, y = Dim.2, label = paste(nome, "-", toupper(partido))),
                   colour = "black", alpha = 0.5, size = 9, hjust = -.15) 
dev.off()  

# Número de deputados da bancada por clust
n_dep <- mca_obs_df %>% 
  filter(destaque_bancada_direitos_humanos == TRUE) %>% 
  select(clust) %>% 
  table()

p <- ggplot(data = filter(mca_obs_df, destaque_bancada_direitos_humanos), 
            aes(x = reorder(clust, n_dep[clust]), fill = clust)) + 
  geom_bar(width = .5) + 
  theme_pander() + 
  scale_fill_manual(values = c("#fdcdac", "#f4cae4", "#b3e2cd", "#cbd5e8")) +
  labs(y='Nº de Deputados', x='') +
  theme(axis.ticks = element_blank(), 
        axis.text = element_text(size = rel(1.5)), 
        legend.position="none") + 
  coord_flip()

png("plot/bancadas/bancada_direitos_humanos_n_clust.png", width = 850, height = 500)
p 
dev.off()

# Proporção dos deputados que fazem parte da bancada dos direitos humanos
toPlot <- mca_obs_df %>% 
  group_by(clust, destaque_bancada_direitos_humanos) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>% 
  ungroup() %>% 
  arrange(clust, -destaque_bancada_direitos_humanos, perc)

p <- ggplot(toPlot, aes(x = clust, y = perc, fill = destaque_bancada_direitos_humanos)) +  
  geom_bar(stat = "identity", width = .4) + 
  theme_pander() + 
  scale_y_continuous(labels=percent) + 
  labs(x = "", y = "% dos deputados que são da bancada dos direitos humanos") + 
  theme(legend.position="none", 
        axis.text = element_text(size = rel(1.5))) + 
  scale_fill_brewer(palette = "OrRd") + 
  coord_flip()

png("plot/bancadas/bancada_direitos_humanos_proporcao_clust.png", width = 850, height = 500)
p
dev.off()
```

Bancada bbb

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
# Destaque dos deputados que fazem parte da bancada BBB
bbb <- filter(mca_obs_df, destaque_bancada_bala == TRUE | destaque_bancada_evangelica == TRUE | destaque_bancada_ruralista == TRUE)

p <- plotCluster(mca_obs_df) + 
  geom_point(data = bbb, 
             size = 9, alpha = 0.3, colour = "Black")  +
  coord_equal() 

png("plot/bancadas/bancada_bbb_clust.png", width = 800, height = 600)
p 
dev.off()

# Número de deputados da bancada por clust
n_dep <- bbb %>%
  select(clust) %>% 
  table()

p <- ggplot(data = bbb, 
            aes(x = reorder(clust, n_dep[clust]), fill = clust)) + 
  geom_bar(width = .5) + 
  theme_pander() + 
  scale_fill_manual(values = c("#fdcdac", "#f4cae4", "#b3e2cd", "#cbd5e8")) +
  labs(y='Nº de Deputados', x='') +
  theme(axis.ticks = element_blank(), 
        axis.text = element_text(size = rel(1.5)), 
        legend.position="none") + 
  coord_flip()

png("plot/bancadas/bancada_bbb_n_clust.png", width = 850, height = 500)
p 
dev.off()

# Proporção dos deputados que fazem parte da bancada bbb
mca_obs_df$destaque_bbb <- mca_obs_df$nome %in% bbb$nome

toPlot <- mca_obs_df %>% 
  group_by(clust, destaque_bbb) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>% 
  ungroup() %>% 
  arrange(clust, -destaque_bbb, perc)

p <- ggplot(toPlot, aes(x = clust, y = perc, fill = destaque_bbb)) +  
  geom_bar(stat = "identity", width = .4) + 
  theme_pander() + 
  scale_y_continuous(labels=percent) + 
  labs(x = "", y = "% dos deputados que são da bancada bbb") + 
  theme(legend.position="none", 
        axis.text = element_text(size = rel(1.5))) + 
  scale_fill_brewer(palette = "OrRd") + 
  coord_flip()

png("plot/bancadas/bancada_bbb_proporcao_clust.png", width = 850, height = 500)
p
dev.off()
```
