---
title: "comparativo-das-votacoes"
author: "Rodolfo Viana"
date: "29-10-2015"
output: html_document
---

Verifica quais são os meses/semanas/dias que mais tem votações na camâra.

Bibliotecas necessárias 

```{r}
library(ggplot2)
library(dplyr)
require(scales)

source("R/camara-lib.R")
```

Carregando CSV com os votos dos deputados

```{r}
votos <- ler_votos_de_ativos("votacoes.csv")
proposicoes <- as.data.frame(unique(votos[,c("tipo", "num_pro")]))

votos$bbb  <- votos$num_pro %in%  c("13",
                                    "49",
                                    "171",
                                    "182",
                                    "215",
                                    "352",
                                    "443",
                                    "682",
                                    "846",
                                    "1030",
                                    "1117",
                                    "1121",
                                    "1125",
                                    "1129",
                                    "2016",
                                    "2727",
                                    "2738",
                                    "2971",
                                    "4330",
                                    "8530")

# distinguir diferentes votações de uma mesma proposição
votos$num_pro <- paste0(votos$num_pro, "-", votos$id_votacao)
```

Formatação das datas

```{r}
votos$data <- as.Date(votos$data, format = "%d/%m/%Y")
votacoes <- unique(votos[,c("data", "num_pro", "bbb")])
votacoes$ano <- as.numeric(format(votacoes$data, format = '%Y'))
votacoes$mes <- as.numeric(format(votacoes$data, format = '%m'))
votacoes$dia <- as.numeric(format(votacoes$data, format = '%j'))
votacoes$semana <- as.numeric(format(votacoes$data, format = '%W'))

votacoes <- votacoes %>%
  filter(ano >= 2015)
```

Quantidade de votação mês a mês

```{r}
plot <- quantidade_votacao_mes(votacoes)
plot$nome_mes <- month.abb[plot$mes]

p <- ggplot(data = plot, aes(x=reorder(nome_mes, mes), y = n_votacoes)) + 
  geom_bar(stat="identity") + 
  labs(y='Número de Votações', x='Mês', title = "Número de votações ao mês") + 
  theme_classic() + 
  theme(axis.ticks = element_blank())

png("plot/numero_votacao_mes_1.png", 
    width = 800, height = 600)
p
dev.off()
```

Quantidade de votação dia a dia

```{r}
plot <- quantidade_votacao_dia(votacoes)

plot$destaque <- ifelse(plot$dia == 216, "Rombimento com o Governo", ifelse(plot$dia == 281, "Contas na Suiça", ""))

p <- ggplot(data = plot, aes(x=reorder(dia, dia), y = n_votacoes, group=1)) + 
  geom_line() +
  geom_point() + 
  labs(y='Número de Votações', x='Dia', title = "Número de votações ao dia") + 
  theme_classic() + 
  theme(axis.ticks = element_blank(),
        axis.text.x=element_blank()) +
  scale_y_continuous(breaks = round(seq(min(plot$n_votacoes), max(plot$n_votacoes), by = 1),))

p <- p + geom_point(data = filter(plot, destaque == "Rombimento com o Governo"), 
                    colour = "darkred", 
                    size = 8, 
                    alpha = 0.7)

p <- p + geom_point(data = filter(plot, destaque == "Contas na Suiça"), 
                    colour = "darkred", 
                    size = 8, 
                    alpha = 0.7)

png("plot/numero_votacao_dia_1.png", 
    width = 800, height = 600)
p
dev.off()
```

Quantidade de votação semana a semana

```{r}
plot <- quantidade_votacao_semana(votacoes)
plot$semana
p <- ggplot(data = plot, aes(x=reorder(semana, semana), y = n_votacoes)) + 
  geom_bar(stat="identity") + 
  labs(y='Número de Votações', x='Semana', title = "Número de votações na semana") + 
  theme_classic() + 
  theme(axis.ticks = element_blank()) +
  scale_y_continuous(breaks = round(seq(min(plot$n_votacoes), max(plot$n_votacoes), by = 1),))

png("plot/numero_votacao_semana_1.png", 
    width = 800, height = 600)
p
dev.off()
```


Quantidade de votação semana a semana BBB/não BBB

```{r}
plot <- quantidade_votacao_semana_bbb(votacoes)
library(tidyr)

plot <- plot %>%
  gather(tipo, n_votacoes, votacoes_BBB:votacoes_nao_bbb)

toPlot_nova_semana <- filter(plot, tipo == "votacoes_BBB")
toPlot_nova_semana$new_x <- toPlot_nova_semana$semana  + 0.1

toPlot_nova_semana_nao_bbb <- filter(plot, tipo == "votacoes_nao_bbb")
toPlot_nova_semana_nao_bbb$new_x <- toPlot_nova_semana_nao_bbb$semana 

toPlot <- rbind(toPlot_nova_semana_nao_bbb,toPlot_nova_semana)

p <- ggplot(data = toPlot, aes(x=reorder(semana, semana), y = n_votacoes, colour = tipo)) + 
  geom_point() + 
  labs(y='Número de Votações', x='Semana', title = "Número de votações na semana") + 
  theme_classic() + 
  theme(axis.ticks = element_blank()) 

png("plot/numero_votacao_semana_2.png", 
    width = 800, height = 600)
p
dev.off()
```

Tipo de votações 

```{r}
proposicoes$tipo <- as.character(proposicoes$tipo)
plot <- as.data.frame(table(proposicoes$tipo))

p <- ggplot(data = plot, aes(x=reorder(Var1, -Freq), y = Freq)) + 
  geom_bar(stat="identity") + 
  labs(y='Número de Proposições', x='Tipo', title = 'Número de Proposições Votadas') + 
  theme_classic() + 
  theme(axis.ticks = element_blank())

png("plot/numero_de_proposicoes_1.png", 
    width = 800, height = 600)
p
dev.off()
```

Tipo de votações BBB e não BBB

```{r}
proposicoes$num_pro <- as.character(proposicoes$num_pro)

proposicoes$bbb  <- proposicoes$num_pro %in% c("13",
                                            "49",
                                            "171",
                                            "182",
                                            "215",
                                            "352",
                                            "443",
                                            "682",
                                            "846",
                                            "1030",
                                            "1117",
                                            "1121",
                                            "1125",
                                            "1129",
                                            "2016",
                                            "2727",
                                            "2738",
                                            "2971",
                                            "4330",
                                            "8530")

plot <- as.data.frame(table(proposicoes$bbb))

p <- ggplot(data = plot, aes(x=reorder(Var1, -Freq), y = Freq)) + 
  geom_bar(stat="identity") + 
  labs(y='Número de Proposições', x='Tipo', title = 'Número de Proposições BBB') + 
  theme_classic() + 
  theme(axis.ticks = element_blank())

png("plot/numero_de_proposicoes_2.png", 
    width = 800, height = 600)
p
dev.off()
```
