---
title: "concordância-governo-partidos"
author: "Rodolfo Viana"
date: "22-10-2015"
output: html_document
---


Mostra qual o nível de concordância dos partidos com o governo. 

Bibliotecas necessárias 

```{r}
library(ggplot2)
library(dplyr)
require(scales)

source("R/camara-lib.R")
```

Carregando CSV com os votos dos deputados

```{r}
votos <- ler_votos_de_ativos("votacoes.csv")

# distinguir diferentes votações de uma mesma proposição
votos$num_pro <- paste0(votos$num_pro, "-", votos$id_votacao)

votos$pro_orientacao <- paste0(votos$num_pro, "-", votos$orientacao_partido)

votos$mes <- as.numeric(format(as.Date(votos$data, format = "%d/%m/%Y"),'%m'))
votos$ano <- as.numeric(format(as.Date(votos$data, format = "%d/%m/%Y"),'%Y'))
votos <- filter(votos, ano >=2015)
```

Orientação de cada partido para cada votação

```{r}
orientacao_partidos <- unique(votos[,c("data", "partido", "pro_orientacao")])
orientacao_partidos$ano <- as.numeric(format(as.Date(orientacao_partidos$data, format = "%d/%m/%Y"),'%Y'))
orientacao_partidos$mes <- as.numeric(format(as.Date(orientacao_partidos$data, format = "%d/%m/%Y"),'%m'))

orientacao_partidos <- orientacao_partidos %>%
  filter(ano >= 2015)

orientacao_pt <- orientacao_partidos %>%
  filter(partido == "pt")

orientacao_pmdb <- orientacao_partidos %>%
  filter(partido == "pmdb")

orientacao_psdb <- orientacao_partidos %>%
  filter(partido == "psdb")

orientacao_psol <- orientacao_partidos %>%
  filter(partido == "psol")
```

Comparação da orientação do governo com a orientação dos outros partidos. 

```{r}
pmdb <- concordancia(orientacao_pt$pro_orientacao, orientacao_pmdb$pro_orientacao)
psdb <- concordancia(orientacao_pt$pro_orientacao, orientacao_psdb$pro_orientacao)
psol <- concordancia(orientacao_pt$pro_orientacao, orientacao_psol$pro_orientacao)

concordancia_governo <- data.frame(Concordancia = c(pmdb, psdb, psol), Partidos = c("pmdb", "psdb", "psol"))

p <- ggplot(data = concordancia_governo, aes(x=reorder(Partidos, -Concordancia), y = Concordancia)) + 
  geom_bar(stat="identity") + 
  labs(y='Concordância com o Governo', x='Partidos') +
  theme_classic() +
   theme(panel.background=element_blank())

png("plot/concordancia_1.png", 
    width = 800, height = 600)
p
dev.off()
```

Comparação entre o governo e outros partidos mês a mês 

```{r}
concordancia_mes <- function(partidoA, partidoB){
  df <- data.frame()
  mes <- unique(partidoA$mes)
  
  for (m in mes){
    partidoA_mes <-  partidoA %>%
      filter(mes == m)
    
    partidoB_mes <-  partidoB %>%
      filter(mes == m)
    
    
    df <- rbind(df, data.frame(Concordancia = concordancia(partidoA_mes$pro_orientacao, partidoB_mes$pro_orientacao), Mes = m))
  }
  df
}

pt_pmdb <- concordancia_mes(orientacao_pt, orientacao_pmdb)
pt_pmdb$partido <- "pmdb"

pt_psdb <- concordancia_mes(orientacao_pt, orientacao_psdb)
pt_psdb$partido <- "psdb"

pt_psol <- concordancia_mes(orientacao_pt, orientacao_psol)
pt_psol$partido <- "psol"  

plot <- rbind(pt_pmdb, pt_psdb, pt_psol)
plot$nome_mes <- month.abb[plot$Mes]

# write.csv(plot, file = "plot.csv", row.names= FALSE)
# plot <- read.csv("~/Projetos/houseofcunha/plot.csv")

p <- ggplot(data = plot, aes(x=reorder(nome_mes, Mes), y = Concordancia, group=partido,  colour=partido)) + 
  geom_line() +
  geom_point() + 
    scale_colour_manual(values = c(alpha("darkred", 1), 
                                 alpha("#0066CC", 1),
                                 alpha("#E69F00", 1)), 
                      guide = guide_legend(title = "Partido", 
                                           override.aes = list(alpha = 1, size = 4))) +
  ylab("Concordância com o Governo") + xlab("Mês") +  
  facet_grid(partido ~ .) +
  theme_classic() + 
  theme(axis.ticks = element_blank())

png("plot/concordancia_mes_a_mes_1.png", 
    width = 800, height = 600)
p
dev.off()

# PAREI AQUI. CONTAR VOTAÇÕES POR MÊS
votos %>% group_by(mes) %>% mutate(votados = NROW(unique(num_pro)))
  
```

