---
title: "Visão dos votos"
author: "Nazareno Andrade e João Arthur B. Monteiro"
date: "30 de maio de 2015"
output: html_document
---

Bibliotecas necessárias 

```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
require(cluster)
require(ade4)
require(scales)
require(FactoMineR)

source("R/camara-lib.R")

# para instalar o rCharts:
# require(devtools)
# install_github('rCharts', 'ramnathv')
require("rCharts")
```

Carregando CSV com os votos dos deputados

```{r}
votos <- ler_votos_de_ativos("votacoes.csv")
quant_tipo_pro <- unique(votos[,c("tipo","num_pro")])

# distinguir diferentes votações de uma mesma proposição
votos$num_pro <- paste0(votos$num_pro, "-", votos$id_votacao)
quant_tipo_votacao <- unique(votos[,c("tipo","num_pro")])
```



```{r}
votacao <- votos %>% 
  select(nome, partido, uf, num_pro, voto)

# votacao.detalhes <- votos %>% 
#   select(nome, partido, uf, num_pro, voto, objetivo, cunha)
# write.csv(votacao.detalhes, "detalhada.csv")

# versão do dataframe com recomendações do PMDB sendo a
# votação de Eduardo Cunha:
ec.v <- votos %>% 
  select(num_pro, cunha) %>% 
  filter(cunha %in% c("sim", "não")) %>% 
  unique()

ec <- cbind(data.frame(nome = "Eduardo Cunha", 
                       partido = "pmdb", 
                       uf = "rj"), 
            ec.v)
names(ec) <- names(votacao)
# esse é o df com cunha:
votacao.cc <- rbind(votacao, ec)
```

```{r}
# TODO para agrupar:
# dispensar a coluna de nome 
#rownames(votacao.cast) <- votacao.cast$nome
#votacao.cast <- select(votacao.cast, -1)
#diss <- daisy(votacao.cast[,2:ncol(votacao.cast)], metric = "gower") # stand = FALSE?
```

```{r}
votacao.cast <- dcast(votacao.cc, 
                      nome + partido + uf ~ num_pro, 
                      value.var = "voto")
votacao.cast <- as.data.frame(apply(votacao.cast, 2, as.factor))

mca1 = MCA(votacao.cast, 
           ncp = 2, # Default is 5 
           graph = FALSE,
           quali.sup = c(1:3),
           na.method = "Average") # NA or Avarege

summary(mca1)

plot(mca1,invisible=c("ind","quali.sup","quanti.sup"))

# data frame with observation coordinates
mca1_obs_df = data.frame(mca1$ind$coord, 
                         nome = votacao.cast$nome,
                         partido = votacao.cast$partido, 
                         uf = votacao.cast$uf)

# Alguns notáveis: 
# "Tiririca", "Luiz Couto", "Jandira Fegalli", "Marco Feliciano", "Romário", "Celso Russomano", "Lindemberg Farias", "Manoela D'Ávila", "Chico Alencar"
mca1_obs_df$destaque <- mca1_obs_df$nome %in% c("Tiririca", 
                                                "Pr. Marco Feliciano", 
                                                "Jair Bolsonaro", 
                                                "Luiz Couto", 
                                                "Jandira Feghali",
                                                "Jean Wyllys", 
                                                "Veneziano Vital do Rêgo")

# Destaque dos dep que se tornaram ministros
mca1_obs_df$destaque_ministros  <- mca1_obs_df$nome %in% c("Celso Pansera",
                                "André Figueiredo",
                                "Marcelo Castro"
                                )

# Destaque dos dep que pediram a cassação de Cunha 
mca1_obs_df$destaque_cassacao  <- mca1_obs_df$nome %in% c("Adelmo Carneiro Leão",
                                "Afonso Florence",
                                "Alessandro Molon",
                                "Ana Perugini",
                                "Angelim",
                                "Arnaldo Jordy",
                                "Assis do Couto",
                                "Beto Faro",
                                "Bohn Gass",
                                "Cabo Daciolo",
                                "Chico Alencar",
                                "Chico D Angelo",
                                "Décio Lima",
                                "Edmilson Rodrigues",
                                "Enio Verri",
                                "Erika Kokay",
                                "Givaldo Vieira",
                                "Glauber Braga",
                                "Henrique Fontana",
                                "Hugo Leal",
                                "Heitor Schuch",
                                "Ivan Valente",
                                "Jarbas Vasconcelos",
                                "Jean Wyllys",
                                "João Daniel",
                                "Jorge Solla",
                                "Jose Stédile",
                                "Leonardo Monteiro",
                                "Leônidas Cristino",
                                "Luiz Couto",
                                "Luiza Erundina",
                                "Luizianne Lins",
                                "Marcon",
                                "Margarida Salomão",
                                "Maria do Rosário",
                                "Moema Gramacho",
                                "Nilto Tatto",
                                "Padre João",
                                "Paulão",
                                "Paulo Pimenta",
                                "Pedro Uczai",
                                "Pepe Vargas", # Não achei esse deputado
                                "Professora Marcivania",
                                "Wadih Damous",
                                "Zé Carlos",
                                "Zeca Dirceu")

# Os da PB
mca1_obs_df$destaque_pb <- ifelse(mca1_obs_df$uf == "PB", "PB", "Demais estados")

# Partidos icônicos
mca1_obs_df$destaque_partido = factor(ifelse(mca1_obs_df$partido %in% 
                                               c("pmdb", "psdb", "pt", "psol"), 
                                             as.character(mca1_obs_df$partido), 
                                             "outros"))


mca1_obs_df$destaque_cassacao_partido <-  ifelse(mca1_obs_df$destaque_cassacao == TRUE, as.character(mca1_obs_df$destaque_partido ), "não assinaram")

mca1_obs_df$destaque_cassacao_pt <-  ifelse(as.character(mca1_obs_df$partido) == "pt", ifelse(mca1_obs_df$destaque_cassacao == TRUE, "assinaram", "não assinaram"), "outros partidos")

# E E. Cunha
mca1_obs_df$destaque_cunha <- ifelse(mca1_obs_df$nome == "Eduardo Cunha", TRUE, FALSE)

```

Visão geral

```{r}
plotMCA <- function(dados){
  ggplot(data = semcunha, aes(x = Dim.1, y = Dim.2, label = nome)) +
    geom_hline(yintercept = 0, colour = "gray70") +
    geom_vline(xintercept = 0, colour = "gray70") +
    #geom_point(colour = "gray50", alpha = 0.7) +
    geom_text(colour = "gray50", alpha = 0.7, size =3) +
    #geom_density2d(colour = "gray75") +
    ylab("") + xlab("")+ 
    theme_classic() + 
    theme(axis.ticks = element_blank(), 
          axis.text = element_blank(), 
          axis.line = element_blank())
}

# plot of variable categories
semcunha <- filter(mca1_obs_df, nome != "Eduardo Cunha")
p <- plotMCA(semcunha)
p

cassacao <- filter(mca1_obs_df, destaque_cassacao == TRUE)

png("visao-geral.png", width = 800, height = 600)
p
dev.off()

png("visao-geral-gg.png", width = 1500, height = 1200)
p
dev.off()

p <- p + geom_point(data = filter(mca1_obs_df, nome == "Eduardo Cunha"), 
                    colour = "darkred", 
                    size = 15, 
                    alpha = 0.7)

png("visao-geral-cc.png", width = 800, height = 600)
p
dev.off()

```

Gráfico com os deputados que pediram a cassação de Cunha em destaque

```{r}
p <- ggplot(data = mca1_obs_df, 
       aes(x = Dim.1, y = Dim.2, label = nome, 
           colour = destaque_cassacao_partido)) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_text(size = 3.) +
  scale_colour_manual(values = c(alpha("grey70", .4),
                                 alpha("#018571", 1), 
                                 alpha("darkred", 1), 
                                 alpha("#E69F00", 1),
                                  alpha("#FF3300", 1)                      
                                 ), 
                      guide = guide_legend(title = "Partido", 
                                           override.aes = list(alpha = 1, size = 4))) + 
  ylab("") + xlab("")+ 
  theme_classic() + 
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        axis.line = element_blank())

p <- p + geom_point(data = filter(mca1_obs_df, nome == "Eduardo Cunha"), 
                    colour = "darkred", 
                    size = 15, 
                    alpha = 0.7)


png("cassacao_4.png", 
    width = 800, height = 600)
p
dev.off()


p <- ggplot(data = mca1_obs_df, 
       aes(x = Dim.1, y = Dim.2, label = nome, 
           colour = destaque_cassacao_pt)) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_text(size = 3.) +
  scale_colour_manual(values = c(alpha("darkred", 1),
                                 alpha("black", 1),
                                 alpha("grey70", .4)                   
                                 ), 
                      guide = guide_legend(title = "", 
                                           override.aes = list(alpha = 1, size = 4))) + 
  ylab("") + xlab("")+ 
  theme_classic() + 
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        axis.line = element_blank())

p <- p + geom_point(data = filter(mca1_obs_df, nome == "Eduardo Cunha"), 
                    colour = "darkred", 
                    size = 15, 
                    alpha = 0.7)


png("cassacao_pt_assinaram.png", 
    width = 800, height = 600)
p
dev.off()
```

Gráfico com os deputados que agora são ministros

```{r}
p <- ggplot(data = mca1_obs_df, 
       aes(x = Dim.1, y = Dim.2, label = nome, 
           colour = destaque_ministros)) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_text(size = 3.) +
  scale_colour_manual(values = c(alpha("grey70", .6), 
                                 alpha("black", 1))) + 
  ylab("") + xlab("")+ 
  theme_classic() + 
   theme(legend.position = "none", 
        axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        axis.line = element_blank())

p <- p + geom_point(data = filter(mca1_obs_df, nome == "Eduardo Cunha"), 
                    colour = "darkred", 
                    size = 15, 
                    alpha = 0.7)


png("plot/novos_ministros.png", 
    width = 800, height = 600)
p
dev.off()
```

Alguns ilustres

```{r}
p <- ggplot(data = semcunha, 
            aes(x = Dim.1, y = Dim.2, label = nome, colour = destaque, size = destaque)) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_text() +
  scale_size_manual(values = c(3.2, 4)) + 
  scale_colour_manual(values = c(alpha("grey70", .6), 
                                 alpha("black", 1))) + 
  ylab("") + xlab("")+ 
  theme_classic() + 
  theme(legend.position = "none", 
        axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        axis.line = element_blank())

p
png("icones.png", 
    width = 800, height = 600)
p
dev.off()

```

Partidos

```{r}
p <- ggplot(data = semcunha, 
       aes(x = Dim.1, y = Dim.2, label = nome, 
           colour = destaque_partido)) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_text(size = 3.) +
  scale_colour_manual(values = c(alpha("grey70", .6), 
                                 alpha("darkred", 1), 
                                 alpha("#0066CC", 1),
                                 alpha("#E69F00", 1),
                                 alpha("#FF3300", 1)
                                 ), 
                      guide = guide_legend(title = "partido", 
                                           override.aes = list(alpha = 1, size = 4))) + 
  ylab("") + xlab("")+ 
  theme_classic() + 
  theme(axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        axis.line = element_blank())
p
png("plot/partidos.png", 
    width = 800, height = 600)
p
dev.off()

png("plot/partidos-gg.png", width = 1500, height = 1200)
p
dev.off()
```

O pessoal da PB 

```{r}
p <- ggplot(data = semcunha, 
            aes(x = Dim.1, 
                y = Dim.2, 
                label = nome, 
                colour = destaque_pb, 
                size = destaque_pb == "PB")) +
  geom_hline(yintercept = 0, colour = "gray70") +
  geom_vline(xintercept = 0, colour = "gray70") +
  geom_text() +
  scale_colour_manual(values = c(alpha("grey70", .5), 
                                 alpha("black", 1))) + 
  scale_size_manual(values = c(3.2, 4)) + 
  ylab("") + xlab("")+ 
  theme_classic() + 
  theme(legend.position = "none", 
        axis.ticks = element_blank(), 
        axis.text = element_blank(), 
        axis.line = element_blank())

png("deputados-da-pb.png", 
    width = 800, height = 600)
p
dev.off()

```

Interativo

```{r}
options(RCHART_WIDTH = 800, RCHART_HEIGHT = 500)
n1 <- nPlot(Dim.2 ~ Dim.1, 
            group = 'destaque_partido', 
            data = semcunha, 
            type = "scatterChart")
n1$chart(color = c("#BDBDBD", "#FF3300", "darkred", "#0066CC", "#E69F00"))
n1$chart(tooltipContent = "#! function(key, x, y, e){ 
  return e.point.nome + ', ' + (e.point.partido.toUpperCase()) + '(' + (e.point.uf) + ')';
} !#")
n1$chart(tooltipXContent = NA, tooltipYContent = NA)
n1$chart(sizeRange = c(50,50))
n1$chart(showXAxis = FALSE, showYAxis = FALSE)
n1

n1$save("partidosdestaque.html", cdn=TRUE)
#n1$publish('House of Cunha - alguns partidos', host = 'gist')
sink("viz-inline.html")
cat(n1$show('inline', include_assets = TRUE, cdn = TRUE))
sink()
n1
```

Proporção por cada PEC / Votação

```{r}

quant_tipo_pro$tipo <- as.character(quant_tipo_pro$tipo)
p <- ggplot(as.data.frame(table(quant_tipo_pro$tipo)), aes(x=reorder(Var1, -Freq), Freq)) + geom_bar(stat = "identity") +
  labs(title = "Proporção do tipo de votação", x = "", y = "") +
  theme_classic()

png("prop-votacao.png", 
    width = 800, height = 600)
p
dev.off()


quant_tipo_votacao$tipo <- as.character(quant_tipo_votacao$tipo)
p <- ggplot(as.data.frame(table(quant_tipo_votacao$tipo)), aes(x=reorder(Var1, -Freq), Freq)) + geom_bar(stat = "identity") +
  labs(title = "Proporção de cada tipo de votação", x = "", y = "") + 
  theme_classic()

png("prop-cada-votacao.png", 
    width = 800, height = 600)
p
dev.off()

```
