---
title: "mapa-das-votacoes-mes-a-mes"
author: "Arthur/Rodolfo"
date: "09-11-2015"
output: html_document
---

Compara as posições dos deputados federais considerando os votos em cada proposição mês a mês. 

```{r, warning=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
require(scales)

source("~/Projetos/houseofcunha/R/camara-lib.R")
```

Carregando CSV com os votos dos deputados

```{r, warning=FALSE, message=FALSE}
votos <- ler_votos_de_ativos("~/Projetos/houseofcunha/votacoes.csv")

# distinguir diferentes votações de uma mesma proposição
votos$num_pro <- paste0(votos$num_pro, "-", votos$id_votacao)
```

Formatação das datas

```{r}
votos$data <- as.Date(votos$data, format = "%d/%m/%Y")
votos$ano_votacao <- as.numeric(format(votos$data, format = '%Y'))
votos$mes <- as.numeric(format(votos$data, format = '%m'))

votos <- votos %>%
  filter(ano_votacao >= 2015)
```

```{r}
geraMCA <-  function(votos){
  votacao <- votos %>% 
    select(nome, partido, uf, num_pro, voto)
  
  # versão do dataframe com recomendações do PMDB sendo a
  # votação de Eduardo Cunha:
  ec.v <- votos %>% 
    select(num_pro, cunha) %>% 
    filter(cunha %in% c("sim", "não")) %>% 
    unique()
  
  ec <- cbind(data.frame(nome = "Eduardo Cunha", 
                         partido = "pmdb", 
                         uf = "rj"), 
              ec.v)
  names(ec) <- names(votacao)
  # esse é o df com cunha:
  votacao.cc <- rbind(votacao, ec)
  
  votacao.cast <- dcast(votacao.cc, 
                        nome + partido + uf ~ num_pro, 
                        value.var = "voto")
  
  votacao.cast <- as.data.frame(apply(votacao.cast, 2, as.factor))
  
  mca1 = MCA(votacao.cast, 
             ncp = 2, # Default is 5 
             graph = FALSE,
             quali.sup = c(1:3),
             na.method = "Average") # NA or Avarege
  
  # data frame with observation coordinates
  mca1_obs_df = data.frame(mca1$ind$coord, 
                           nome = votacao.cast$nome,
                           partido = votacao.cast$partido, 
                           uf = votacao.cast$uf)
  
  # Partidos icônicos
  mca1_obs_df$destaque_partido = factor(ifelse(mca1_obs_df$partido %in% 
                                                 c("pmdb", "psdb", "pt", "psol"), 
                                               as.character(mca1_obs_df$partido), 
                                               "outros"))
  
  mca1_obs_df
}

mca <- geraMCA(filter(votos, mes < 3))
plotMCA(mca)

mca <- geraMCA(filter(votos, mes < 4))
plotMCA(mca)

mca <- geraMCA(filter(votos, mes < 5))
plotMCA(mca)

mca <- geraMCA(filter(votos, mes < 6))
plotMCA(mca)

mca <- geraMCA(filter(votos, mes < 7))
plotMCA(mca)

mca <- geraMCA(filter(votos, mes < 8))
plotMCA(mca)

mca <- geraMCA(filter(votos, mes < 9))
plotMCA(mca)


mca <- geraMCA(filter(votos, mes < 10))
plotMCA(mca)
```
