---
title: "mapa-impeachment"
output: html_document
---

Comparação das chapas do governo e oposição para formar a chapa especial de análise do impeachment.

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
require(FactoMineR)
library(dplyr)
library(ggthemes)
require(scales)

source("R/camara-lib.R")
```


```{r}
votos_por_deputado <- recuperar_votos_por_deputado(arquivo.votos = "dados/votacoes.csv", corrigir.migracoes = TRUE)

mca <- MCA(votos_por_deputado, 
           ncp = 5, # Default is 5 
           graph = FALSE,
           quali.sup = c(1:4),
           na.method = "Average") # NA or Average

mca_obs_df <-  data.frame(mca$ind$coord, 
                           nome = votos_por_deputado$nome,
                           partido = votos_por_deputado$partido, 
                           uf = votos_por_deputado$uf,
                           id_dep = votos_por_deputado$id_dep)

mca_obs_df$id_dep <- as.integer(as.character(mca_obs_df$id_dep))

#mca_obs_df <- filter(mca_obs_df, id_dep != 191923)

#Criação do clust
hcpc <- clusterizar(mca,4)
clusters <- obter_clusters(hcpc)

mca_obs_df <- cbind(mca_obs_df, select(clusters,clust))
mca_obs_df$clust <- as.factor(mca_obs_df$clust)

# Add Dep Feliciano
mca_aux <- filter(mca_obs_df, id_dep == 160601)
mca_aux$nome <- "Pastor Marco Feliciano"
mca_obs_df <- rbind(mca_obs_df, mca_aux) 

# Add Dep João Marcelo Souza
mca_aux <- filter(mca_obs_df, id_dep == 112437)
mca_aux$nome <- "João Marcelo Souza"
mca_obs_df <- rbind(mca_obs_df, mca_aux) 

# Add Dep Jerônimo Goergen
mca_aux <- filter(mca_obs_df, id_dep == 160570)
mca_aux$nome <- "Jerônimo Goergen"
mca_obs_df <- rbind(mca_obs_df, mca_aux) 

# Add Dep Nogueira
#dep_Nogueira <- c(-0.09748948, -0.03307884, -0.04056188, -0.05073609, 0.03257657, "Flavio Nogueira", "pdt", "PI", 191923, as.factor(3))
#mca_obs_df <- rbind(mca_obs_df, c(-0.09748948, -0.03307884, -0.04056188, -0.05073609, 0.03257657, "Flavio Nogueira", "pdt", "PI", 191923, 3))

comissao <- read.table("dados/comissao_impeachment.csv", header=TRUE, quote="\"")
mca_obs_df$destaque <- mca_obs_df$nome %in% comissao$Titulares

x <- filter(mca_obs_df, destaque == TRUE)

#y = filter(votos_por_deputado, uf == "RS")
#yy <- filter(y, partido = "pp")

levels(mca_obs_df$clust) <- c("Governo", "Alinhados com PMDB", "Oposição de esquerda", "Oposição")
```

Plots

```{r}
# Destaque dos deputados que fazem parte da comissao
p <- plotCluster(mca_obs_df) + 
  geom_point(data = filter(mca_obs_df, destaque == TRUE), 
             size = 9, alpha = 0.3, colour = "Black")  +
  coord_equal() 

png("plot/impeachment/comissao_impeachment.png", width = 800, height = 600)
p 
dev.off()
```


Número de deputados da comissão por clust e Proporção dos deputados da comissão por clust

```{r}
# Número de deputados da comissao por clust
n_dep <- mca_obs_df %>% 
  filter(destaque == TRUE) %>% 
  select(clust) %>% 
  table()

p <- ggplot(data = filter(mca_obs_df, destaque), 
            aes(x = reorder(clust, n_dep[clust]), fill = clust)) + 
  geom_bar(width = .5) + 
  theme_pander() + 
  scale_fill_manual(values = c("#fdcdac", "#f4cae4", "#b3e2cd", "#cbd5e8")) +
  labs(y='Nº de Deputados', x='') +
  theme(axis.ticks = element_blank(), 
        axis.text = element_text(size = rel(1.5)), 
        legend.position="none") + 
  coord_flip()

png("plot/impeachment/comissao_impeachment_n_clust.png", width = 850, height = 500)
p 
dev.off()

# Proporção dos deputados que fazem parte da comissão
toPlot <- mca_obs_df %>% 
  group_by(clust, destaque) %>% 
  summarise(count=n()) %>% 
  mutate(perc=count/sum(count)) %>% 
  ungroup() %>% 
  arrange(clust, -destaque, perc)

toPlot$order = c(1,1,4,4,2,2,3,3)

p <- ggplot(toPlot, aes(x = reorder(clust, -order), y = perc, fill = destaque)) +  
  geom_bar(stat = "identity", width = .4) + 
  theme_pander() + 
  labs(x = "", y = "% dos deputados que são da comissão") + 
  theme(legend.position="none", 
        axis.text = element_text(size = rel(1.5))) + 
  scale_fill_brewer(palette = "OrRd") + 
  coord_flip()

png("plot/impeachment/comissao_impeachment_proporcao_clust_alt_1.png", width = 850, height = 500)
p
dev.off()

# Plot alternativo 2
toPlot2 <- filter(toPlot, destaque == TRUE)

p <- ggplot(toPlot2, aes(x = reorder(clust, -order), y = perc, fill = destaque)) +  
  geom_bar(stat = "identity", width = .4) + 
  theme_pander() + 
  labs(x = "", y = "% dos deputados que são da comissão") + 
  theme(legend.position="none", 
        axis.text = element_text(size = rel(1.5))) + 
  scale_fill_brewer(palette = "OrRd") + 
  coord_flip()

png("plot/impeachment/comissao_impeachment_proporcao_clust_alt_2.png", width = 850, height = 500)
p
dev.off()

# Plot alternativo 3
toPlot2 <- filter(toPlot, destaque == TRUE)

p <- ggplot(toPlot2, aes(x = reorder(clust, -order), y = perc, fill = clust)) +  
  geom_bar(stat = "identity", width = .4) + 
  theme_pander() + 
  scale_fill_manual(values = c("#fdcdac", "#f4cae4", "#b3e2cd", "#cbd5e8")) +
  labs(x = "", y = "% dos deputados que são da comissão") + 
  theme(legend.position="none", 
        axis.text = element_text(size = rel(1.5))) + 
  coord_flip()

png("plot/impeachment/comissao_impeachment_proporcao_clust_alt_3.png", width = 850, height = 500)
p
dev.off()
```

```{r}
antiga_comissao <- read.table("dados/chapas-impeachment.csv", header=TRUE, quote="\"")
mca_obs_df$destaque <- mca_obs_df$nome %in% comissao$Titulares

# Destaque dos deputados que fazem parte da comissao
p <- plotCluster(mca_obs_df) + 
  geom_point(data = filter(mca_obs_df, destaque == TRUE), 
             size = 9, alpha = 0.3, colour = "Black")  +
  coord_equal() 

png("plot/impeachment/comissao_impeachment.png", width = 800, height = 600)
p 
dev.off()
```