---
title: "pos-votacao-impeachment"
output: html_document
---

Análise sobre a votação do impeachment na câmara do deputados.

Carregando as bibliotecas necessárias

```{r}
require(FactoMineR)
library(ggplot2)
library(dplyr)
require(scales)
#install.packages('tm')
library(tm)

source("R/camara-lib.R")
```

Carregando os dados dos deputados e da votação do impeachment

```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
# Deputados votaçoes de 2015 ate abril de 2016
votos_por_deputado <- recuperar_votos_por_deputado(arquivo.votos = "dados/votacoes.csv", corrigir.migracoes = TRUE)

# Deputados votação impeachment
deputados.votacao.impeachment <- read.csv("~/Projetos/houseofcunha/dados/deputados-votacao-impeachment.csv", sep=";")

# Votação Impeachment Discursos
discursos.impeachment <- read.csv("~/Projetos/houseofcunha/dados/discursos impeachment.csv", stringsAsFactors = FALSE)
voto_impeachment <- select(discursos.impeachment, Deputado, Voto)
```


```{r, warning=FALSE, message=FALSE, fig.align='center', echo=FALSE}
mca <- MCA(votos_por_deputado, 
           ncp = 6, # Default is 5 
           graph = FALSE,
           quali.sup = c(1:4),
           na.method = "Average") # NA or Average

mca_obs_df <-  data.frame(mca$ind$coord, 
                           nome = votos_por_deputado$nome,
                           partido = votos_por_deputado$partido, 
                           uf = votos_por_deputado$uf,
                           id_dep = votos_por_deputado$id_dep)

mca_obs_df$id_dep <- as.integer(as.character(mca_obs_df$id_dep))

#Criação do clust
hcpc <- clusterizar(mca,4)
clusters <- obter_clusters(hcpc)

mca_obs_df <- cbind(mca_obs_df, select(clusters,clust))
mca_obs_df$clust <- as.factor(mca_obs_df$clust)

# Destaque da votação do impeachment 

colnames(deputados.votacao.impeachment)

deputados.votacao.impeachment2 <- deputados.votacao.impeachment[!duplicated(deputados.votacao.impeachment$id_dep), ]
deputados.votacao.impeachment3 <- filter(deputados.votacao.impeachment2, id_dep != 74213)

teste <- left_join(mca_obs_df, select(deputados.votacao.impeachment3, id_dep, IMPEACHMENT), by = "id_dep")

summary(teste$IMPEACHMENT)

X <- filter(teste, IMPEACHMENT == "SIM")
xx <- filter(imp.votacao, voto == "SIM")




mca_obs_df$impeachment <-  mca_obs_df$nome %in% voto_impeachment$Deputado

voto_impeachment$nomes <- voto_impeachment$Deputado  %in%  mca_obs_df$nome

voto_impeachment_false <- filter(voto_impeachment, nomes == FALSE)

teste <- left_join(mca_obs_df, voto_impeachment, by = c("nome" = "Deputado"))

x <- filter(mca_obs_df, impeachment == FALSE)
# sum(mca_obs_df$impeachment)
# y <- filter(mca_obs_df, impeachment == TRUE)

match_deputados <- function(nome.deputados.novo, nome.deputados.original){
  df <- data.frame()

  for (nome in nome.deputados.novo){
    novo_nome <- agrep(nome, nome.deputados.original, ignore.case=T, value=T, max.distance = 0.2, useBytes = FALSE)
    df <- rbind(df, data.frame(nome, ifelse(length(novo_nome) == 0, "NA", novo_nome)))
  }
  
  df
}

nome_deputados <- voto_impeachment_false$Deputado
nome_original <- mca_obs_df$nome

nome.deputados.novo <- nome_deputados
nome.deputados.original <- nome_original

p <- ggplot(data = teste, aes(x = Dim.1, y = Dim.2)) + 
   geom_point(data = teste, size = 9, alpha = 0.3, aes(colour = factor(Voto))) + 
  scale_colour_manual(values = c("red","blue", "green", "gray70", "black")) +
  theme_classic() + 
  theme(axis.ticks = element_blank()) 

png("plot/pos_votacao/mapa_sim_nao_impeachment.png", width = 900, height = 500)
p
dev.off()

levels(mca_obs_df$clust) <- c("Governo", "Alinhados com PMDB", "Oposição de esquerda", "Oposição")
```


```{r}
str(discursos.impeachment)

discursos.impeachment$Fala <- paste0(discursos.impeachment$Fala, " ", discursos.impeachment$X)
discursos.impeachment$X <- NULL

discursos.sim <- filter(discursos.impeachment, Voto == "Sim")
discursos.nao <- filter(discursos.impeachment, Voto == "Não")


frequencia_palavra_discursos <- function (discursos, n_grams = 1){
  review_text <- paste(discursos$Fala, collapse=" ")
  review_source <- VectorSource(review_text)
  corpus <- Corpus(review_source)
  
  corpus <- tm_map(corpus, content_transformer(tolower))
  corpus <- tm_map(corpus, removePunctuation)
  corpus <- tm_map(corpus, stripWhitespace)
  
  ngramTokenizer <- function(x) unlist(lapply(ngrams(words(x), n_grams), paste, collapse = " "), use.names = FALSE)
  
  dtm <- DocumentTermMatrix(corpus, control = list(tokenize = ngramTokenizer))
  dtm2 <- as.matrix(dtm)
  frequency <- colSums(dtm2)
  frequency <- sort(frequency, decreasing = TRUE)
  
  frequency <- as.data.frame(frequency)
  frequency <- cbind(Palavra = rownames(frequency), frequency)
  rownames(frequency) <- NULL
  
  frequency$top <- 1:nrow(frequency)
  
  frequency
}

frequencia.discursos.sim <- frequencia_palavra_discursos(discursos.sim, 1)
frequencia.discursos.nao <- frequencia_palavra_discursos(discursos.nao, 1)

#frequencia.discursos.sim$zipf <- frequencia.discursos.sim$frequency * frequencia.discursos.sim$top
#hist(frequencia.discursos.sim$zipf)

colnames(frequencia.discursos.nao) <- c("Palavra", "frequency", "top_nao")

frequencia.discursos.sim.nao <- left_join(frequencia.discursos.sim, frequencia.discursos.nao, by = "Palavra")

frequencia.discursos.nao.sim <- left_join(frequencia.discursos.nao, frequencia.discursos.sim, by = "Palavra")

palavras_frequentes <- frequencia.discursos.sim.nao[1:200,]$Palavra
palavras_frequentes <- append(palavras_frequentes, frequencia.discursos.nao.sim[1:200,]$Palavra)
palavras_frequentes <- unique(palavras_frequentes)

frequencia.discursos.total <- full_join(frequencia.discursos.sim.nao, frequencia.discursos.nao.sim, by = "Palavra", copy = TRUE)

frequencia.discursos.total$destaque_top <- frequencia.discursos.total$Palavra %in% palavras_frequentes
frequencia.discursos.total <- frequencia.discursos.total[,c(1,2,3,4,5,10)]

frequencia.discursos.total.sample <- filter(frequencia.discursos.total, destaque_top == TRUE)

frequencia.discursos.sim.nao.sample <- frequencia.discursos.sim.nao.sample[complete.cases(frequencia.discursos.sim.nao.sample),]


create_destaque_columns <- function(df, n_palavras = 15) {
  df$diff <- df$top - df$top_nao
  top_sim <- head(df[with(df, order(diff)), ]$Palavra, n_palavras)
  
  df$diff <-  df$top_nao - df$top
  top_nao <- head(df[with(df, order(diff)), ]$Palavra, n_palavras)
  
  palavras_destaque <- append(top_sim, top_nao)
  df$destaque <- df$Palavra %in% palavras_destaque
  
  df
}


frequencia.discursos.sim.nao.sample2 <- create_destaque_columns(frequencia.discursos.sim.nao.sample, 15)



ggplot(data = frequencia.discursos.sim.nao.sample, aes(x = reorder(top, -top), y = reorder(top_nao, -top_nao))) + 
   #geom_point(size = 9, alpha = 0.3) + 
  geom_text(data = frequencia.discursos.sim.nao.sample, 
                   aes(label = toupper(Palavra)),
                   colour = alpha("grey70", .4), alpha = 0.5, size = 5, hjust = -.15) + 
  geom_text(data = filter(frequencia.discursos.sim.nao.sample2, destaque == TRUE), 
                   aes(label =  toupper(Palavra)),
                   colour = "black", alpha = 0.5, size = 5, hjust = -.15) + 
  scale_x_discrete('Discurso SIM', breaks = c(max(frequencia.discursos.sim.nao.sample$top),  median(frequencia.discursos.sim.nao.sample$top), 1),
                     labels=c("base", "meio", "topo")) +
  scale_y_discrete('Discurso NAO', breaks = c(max(frequencia.discursos.sim.nao.sample$top_nao), median(frequencia.discursos.sim.nao.sample$top_nao), 1),
                     labels=c("base", "meio", "topo")) +
  geom_abline(intercept = 0, color = alpha("#762a83", 1)) +
  theme_classic() 


  
```
