---
title: "votacao-dimensao"
author: "Rodolfo Viana"
date: "26-10-2015"
output: html_document
---

Bibliotecas necessárias 

```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
require(cluster)
require(ade4)
require(scales)
require(FactoMineR)

source("R/camara-lib.R")
```

Carregando CSV com os votos dos deputados

```{r}
votos <- ler_votos_de_ativos("votacoes.csv")
votos$ano <- as.numeric(format(as.Date(votos$data, format = "%d/%m/%Y"),'%Y'))
votos <- filter(votos, ano > 2014)

# distinguir diferentes votações de uma mesma proposição
votos$num_pro <- paste0(votos$num_pro, "-", votos$id_votacao)
```



```{r}
votacao <- votos %>% 
  select(nome, partido, uf, num_pro, voto)

# votacao.detalhes <- votos %>% 
#   select(nome, partido, uf, num_pro, voto, objetivo, cunha)
# write.csv(votacao.detalhes, "detalhada.csv")

# versão do dataframe com recomendações do PMDB sendo a
# votação de Eduardo Cunha:
ec.v <- votos %>% 
  select(num_pro, cunha) %>% 
  filter(cunha %in% c("sim", "não")) %>% 
  unique()

ec <- cbind(data.frame(nome = "Eduardo Cunha", 
                       partido = "pmdb", 
                       uf = "rj"), 
            ec.v)
names(ec) <- names(votacao)
# esse é o df com cunha:
votacao.cc <- rbind(votacao, ec)
```


```{r}
votacao.cast <- dcast(votacao.cc, 
                      nome + partido + uf ~ num_pro, 
                      value.var = "voto")
votacao.cast <- as.data.frame(apply(votacao.cast, 2, as.factor))

mca1 <- MCA(votacao.cast, 
           ncp = 2, # Default is 5 
           graph = FALSE,
           quali.sup = c(1:3),
           na.method = "Average") # NA or Avarege


# Melhor representado
plot(mca1, invisible=c("ind","quali.sup","quanti.sup"), cex=0.9,  selectMod ="cos2 0.65")

# Melhor contribuicao
plot(mca1, invisible=c("ind","quali.sup","quanti.sup"), cex=0.9,  selectMod ="contrib 20")


summary(mca1)
barplot(mca1$eig[,1], names.arg = paste("Dim", 1:nrow(res$eig), sep = ""))


contrib_var <- as.data.frame(mca1$var$contrib)
contrib_ind <- as.data.frame(mca1$ind$contrib)
```
